#!/bin/bash

# Launch a tmux session on the server and start ogc_tmux in it. This file should be in /usr/local/bin

tmux new -d -s admin

tmux send-keys -t admin "/usr/local/bin/ogc_tmux" C-m

tmux detach -s admin

exit 0
