#!/bin/bash

#source /opt/ros/noetic/setup.bash
#source /home/ubuntu/Yonah_ROS_packages/ogc_ws/devel/setup.bash
#/home/ubuntu/Yonah_ROS_packages/ogc_ws/src/telegram/src/telegram_bone

#roslaunch telegram telegram_air.launch

tmux new -d -s ogc_session
tmux send-keys -t ogc_session "/usr/local/bin/ogc_tmux" C-m
tmux detach -s ogc_session

exit 0
