#!/usr/bin/env python3

## to be run as part of Yonah_Scripts bonesetup

import os
from ctypes import *
import json
from pathlib import Path
import time

home_dir = str(Path.home())
tdlib_dir = home_dir + '/.tdlib'
self_id_file = home_dir + '/.self_id'

class Td():
	def __init__(self, tdlib_dir):
		tdjson_path = '/usr/local/lib/libtdjson.so'
		tdjson = CDLL(tdjson_path)

		client_create = tdjson.td_json_client_create
		client_create.restype = c_void_p
		client_create.argtypes = []
		self.client = client_create()

		self._client_receive = tdjson.td_json_client_receive
		self._client_receive.restype = c_char_p
		self._client_receive.argtypes = [c_void_p, c_double]

		self._client_send = tdjson.td_json_client_send
		self._client_send.restype = None
		self._client_send.argtypes = [c_void_p, c_char_p]
		
		self._client_execute = tdjson.td_json_client_execute
		self._client_execute.restype = c_char_p
		self._client_execute.argtypes = [c_void_p, c_char_p]
		
		self._client_destroy = tdjson.td_json_client_destroy
		self._client_destroy.restype = None
		self._client_destroy.argtypes = [c_void_p]

		fatal_error_callback_type = CFUNCTYPE(None, c_char_p)

		set_log_fatal_error_callback = tdjson.td_set_log_fatal_error_callback
		set_log_fatal_error_callback.restype = None
		set_log_fatal_error_callback.argtypes = [fatal_error_callback_type]

		fatal_error_cb = fatal_error_callback_type(self._fatal_error_cb)
		set_log_fatal_error_callback(fatal_error_cb)

		self.tdlib_dir = tdlib_dir

		self._execute({
			'@type': 'setLogVerbosityLevel',
			'new_verbosity_level': 1
		})

	def _fatal_error_cb(self, error):
		print('TDLiB fatal error: ', error)

	def _execute(self, query):
		query = json.dumps(query).encode('utf-8')
		result = self._client_execute(None, query)
		if result:
			return json.loads(result.decode('utf-8'))

	def send(self, query):
		query = json.dumps(query).encode('utf-8')
		self._client_send(self.client, query)

	def receive(self):
		result_orig = self._client_receive(self.client, 1.0)
		if result_orig:
			result = json.loads(result_orig.decode('utf-8'))
			recv_type = result['@type']

			if recv_type == 'updateAuthorizationState':
				auth_state = result['authorization_state']['@type']
				if auth_state == 'authorizationStateWaitTdlibParameters':
					self.send({
						'@type': 'setTdlibParameters',
						'parameters': {
							'database_directory': self.tdlib_dir,
							'use_message_database': True,
							'use_secret_chats': True,
							'api_id': 1111226,
							'api_hash': '9996b83ac27902d79ce9486e6f740a08',
							'system_language_code': 'en',
							'device_model': 'Desktop',
							'system_version': 'Linux',
							'application_version': '1.0',
							'enable_storage_optimizer': True
						}
					})
				elif auth_state == 'authorizationStateWaitEncryptionKey':
					self.send({
						'@type': 'checkDatabaseEncryptionKey',
						'key': 'my_key' #need to change this
					})
			elif recv_type == 'users':
				for user_id in result['user_ids']:
					self.send({
						'@type': 'getUser',
						'user_id': user_id
					})

			return result

	# add contact to account
	# needed to add admin account
	def add_contact(self, number, label):
		self.send({
			"@type": "importContacts",
			"contacts": [{
				"@type": "contact",
				"first_name": label,
				"phone_number": "00" + number
			}]
		})

	def get_contacts(self):
		self.send({
			"@type": "getContacts"
		})

	def destroy(self):
		self._client_destroy(self.client)


if __name__ == '__main__':
	if os.path.isdir(tdlib_dir):
		print('An instance of telegram already exists in this directory')
		print('Please delete that instance if you wish to create a new one')
		print('exiting...')
		exit()
	
	td = Td(tdlib_dir)
	td.send({'@type': 'getAuthorizationState'})

	boot_time = time.time()
	admin_number = ""
	admin_id = 0

	while True:
		event = td.receive()
		if event:
			if event['@type'] == 'updateAuthorizationState':
				auth_state = event['authorization_state']['@type']

				if auth_state == 'authorizationStateClosed':
					break

				if auth_state == 'authorizationStateWaitTdlibParameters':
					td.send({
						'@type': 'setTdlibParameters',
						'parameters': {
							'database_directory': tdlib_dir,
							'use_message_database': True,
							'use_secret_chats': True,
							'api_id': 1111226,
							'api_hash': '9996b83ac27902d79ce9486e6f740a08',
							'system_language_code': 'en',
							'device_model': 'Desktop',
							'system_version': 'Linux',
							'application_version': '1.0',
							'enable_storage_optimizer': True
						}
					})

				if auth_state == 'authorizationStateWaitEncryptionKey':
					td.send({
						'@type': 'checkDatabaseEncryptionKey', 
						'key': 'my_key'
					})

				if auth_state == 'authorizationStateWaitPhoneNumber':
					phone_number = input('Please enter your phone number (with country code, eg: 6512345678): ')
					td.send({
						'@type': 'setAuthenticationPhoneNumber', 
						'phone_number': phone_number
					})

				if auth_state == 'authorizationStateWaitCode':
					code = input('Please enter the authentication code you received: ')
					td.send({
						'@type': 'checkAuthenticationCode', 
						'code': code
					})

				if auth_state == 'authorizationStateWaitPassword':
					password = input('Please enter your password')
					td.send({
						'@type': 'checkAuthenticationPassword', 
						'password': password
					})
				if auth_state == 'authorizationStateReady':
					print('telegram client setup complete')
					admin_number = input('please enter the phone number of the admin account (with country code, eg: 6512345678): ')
					td.add_contact(admin_number, "admin")
					td.get_contacts()
					print('waiting for device_id from admin account')

			elif event['@type'] == 'user':
				if event['phone_number'] == admin_number:
					admin_id = event['id']
					print("Received admin_id")

			if event['@type'] == 'updateNewMessage':
				if event['message']['is_outgoing'] or event['message']['date'] < boot_time:
					continue

				print(f"{admin_id} {event['message']['sender_user_id']}")
				if event['message']['sender_user_id'] == admin_id:
					print("received message from admin")
					try:
						msg = json.loads(event['message']['content']['text']['text'])
						if msg['request'] == 'set_device_id':
							with open(self_id_file, 'w') as f:
								f.write(f"{msg['device_id']}\n")
							print("Setup complete!")
							exit()
					except json.JSONDecodeError:
						print("invalid message format")
						continue
